### PR TITLE
Issue 40 home page facebook plugin

### PR DESCRIPTION
**Pull request by Julie-Salazar**
## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**
changed the centering of social medias as well as make all hyperlinked and buttons to 
 change colour when hovered over, having trouble with doing that with the two quick links at the top of the pag
### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

### CODE REVIEW

**Review by seraph1201 — APPROVED** [review]
Nice work!

**Review by seraph1201 — CHANGES_REQUESTED** [review]
Looks good! Just a small issue - the core services links don't work, and clicking on "learn more about us" links you to the donation page

**Review by cjnbennett — APPROVED** [review]
Lgtm

**Comment by seraph1201** [comment]
Still a couple of issues to be fixed:
- responsiveness of the black sheen should be matched to the orange image
- "transitional housing" is too high up
image

Otherwise good job

**Review by seraph1201 — APPROVED** [review]

**Pull request merged**
