### PR TITLE
Issue 93 our people page

### LINKED ISSUE #93: Our People Page
## Basic Information
Create the Our People page as per the figma. It fits under the ['About Us' pages](https://github.com/codersforcauses/starick/issues/7).

### PR DESCRIPTION
**Pull request by Aifert**
## Change Summary
Changed our people page to be the same as figma

### Change Form

- [X ] The pull request title has an issue number
- [X ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

### CODE REVIEW

**Review by cjnbennett — APPROVED** [review]
Great work!

**Comment by cjnbennett** [comment]
Hi @Aifert, I just realised this PR is into the local branch rather than main. Is this intended or was it ready to be merged into main?

**Comment by Aifert** [comment]
> Hi @Aifert, I just realised this PR is into the local branch rather than main. Is this intended or was it ready to be merged into main?

Hi, can I know what the difference is please? The page is ready almost ready to be added to the main website that everyone sees. The only issue now is issue branch 93 does not have the page-header component inside it. So I wasn't able to update the page header to fit exactly like the one in figma. Was thinking I will push this up first. Then fork out the main branch with page-header component, fix the page-header on our people page and push it up again. 

Apologies, still very new to github work flow if you can explain to me what that means that'll be much appreciated!

**Comment by Aifert** [comment]
image

image


This specifically is what I'm talking about, if you merge it into main branch now will get the first photo.

**Comment by cjnbennett** [comment]
> Apologies, still very new to github work flow if you can explain to me what that means that'll be much appreciated!

No worries, thanks for contributing! What you've done so far is fine. I think Celine has invited you to this repository to collaborate (you might need to check your emails). That way you can clone this repository and work on these branches, rather than forking it and cloning your fork. That way you can open pull requests to main, and so on.

Once you've cloned this repo directly, you can `git checkout` this branch and then `git merge main` into it. Then you'll be able to create a commit fixing the issue with the header from main. Once that's done and the branch is "finished", you can create a pull request from the branch into main

Let me know if you need any help doing any of this! If you're planning to come to the CFC Chill Coding session this Friday there will certainly be people there who can help you as well. (I have another commitment at the same time so either won't come at all or will only be able to come for an hour at the end, I'm not sure yet). Feel free to message me on Discord as well!

**Pull request merged**
